WIP: fix error C2131: expression did not evaluate to a constant
The codebase is littered with the GCC-specific dynamic array sizing syntax, which is non-portable. The 'solution' is to review the code while we migrate the declarations to std::vector (std::Array doesn't support support run-time size values either, just like regular C-style arrays)